# Generated by Django 5.0.6 on 2024-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
                ('song_count', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('is_trending', models.BooleanField()),
            ],
        ),
    ]
